# Generated by Django 2.1.7 on 2019-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_auto_20190423_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resfile',
            name='link',
        ),
        migrations.AddField(
            model_name='resfile',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
