# Generated by Django 2.1.7 on 2019-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0004_resfile_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
